### ISSUE TITLE
How to get the summarized experimental results?

### ISSUE THREAD

**Issue by zhenlingcn** [EpistasisLab/srbench#42]
I have executed the experiment script and it outputted several JSON files. However, an issue is that it seems that there is no script that can aggregate these results into a single file. Therefore, my question is, is there any additional analysis tool affiliate with this benchmark package?

**Comment by zhenlingcn** [comment]
I have implemented it by myself.

```python
from glob import glob

import json
import pandas as pd

files = glob('results/*/*.json')
data = []
for f in files:
    with open(f) as ff:
        data.append(json.load(ff))
new_df = pd.DataFrame(data)
```

**Comment by lacava** [comment]
I wanted to mention in commit 63637df41f597d2753e29601ae02fc60aee99890 we added collate scripts to post-processing, so the gap between the `.json` results and saved `.feather` results is eliminated.
