### ISSUE TITLE
instructions to clone pmlb does not work

### ISSUE THREAD

**Issue by folivetti** [EpistasisLab/srbench#43]
the command `git clone https://github.com/EpistasisLab/pmlb/tree/feynman` does not work, it says 

`fatal: repository 'https://github.com/EpistasisLab/pmlb/tree/feynman/' not found`

but using `git clone https://github.com/EpistasisLab/pmlb.git` seems to work ok. The fetch command downloads 299 files in total.

**Comment by folivetti** [comment]
also, after `git lfs fetch` it may be required to do a `git lfs pull`

**Comment by lacava** [comment]
right it should be `git clone -b feynman https://github.com/EpistasisLab/pmlb/`
