### ISSUE TITLE
How do I correctly run the statistical comparison? 

### ISSUE THREAD

**Issue by zhenlingcn** [EpistasisLab/srbench#44]
I am glad that most of this repository is replicable. However, it appears that the statistical comparison part is unable to correctly deal with the provided experiment result. There are several missing values for FEAT and MRGP in the provided file. As a result, the Wilcoxon signed-rank test cannot function properly during the statistical comparison process. So, how should we approach the problem?

**Comment by lacava** [comment]
Hi, can you be more specific? Are you not able to reproduce [this notebook](https://github.com/EpistasisLab/srbench/blob/master/postprocessing/statistical_comparisons.ipynb)? Note it requires running the black-box and ground truth notebooks first to produce summary rankings for the stats comparisons. I described in issue #41 how we handle failed runs for the statistical comparisons. Note that for those comparisons there should be _very few_ missing summary results, and only for AIFeynman. If you're getting a different result from the notebook, please provide details so I can assist.

**Comment by zhenlingcn** [comment]
Okay, thanks for your response. It's true that I should run the black box notebook in advance.  I didn't realize that the notebook requires a file where it comes from the running result of the black box notebook. Thank you for your response. I have solved my problem.

**Comment by lacava** [comment]
I wanted to mention in commit 63637df41f597d2753e29601ae02fc60aee99890 we added collate scripts to post-processing, so the gap between the `.json` results and saved `.feather` results is eliminated.
