### ISSUE TITLE
Support for a better result report

### ISSUE THREAD

**Issue by zhenlingcn** [EpistasisLab/srbench#49]
Now, it seems that the reports generated by those report scripts are too crude. Some important indicators in the AutoML domain, such as significance test and mean accuracy among all tasks, are not presented. In my research domain, there is a benchmark project named "srbench" (https://github.com/EpistasisLab/srbench). It provides a good example for showing above-mentioned metrics. Consequently, I hope this benchmark project can also implement similar features.

**Comment by lacava** [comment]
did you post this to the wrong repo?

**Comment by zhenlingcn** [comment]
Sorry, it's my fault.
