### ISSUE TITLE
broken links on website

### ISSUE THREAD

**Issue by lacava** [EpistasisLab/srbench#50]
@folivetti i'm noticing some of the links on the website are broken, probably because they are copied straight from the markdown files that have relative paths (e.g., `https://epistasislab.github.io/srbench/CONTRIBUTING.md`) 

Do you have any free time to update them? thank you!

**Comment by folivetti** [comment]
sure thing! I'll try to do it later today or, at the latest, by tomorrow.

Should I also put the NeurIPS paper in "Cite" section (marked as accepted for publication)?
